version: "3.7"

services:
  servidor:
    image: tomcat:9.0
    container_name: blogger-client-rest
    ports:
      - 80:8080
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/logs/:/usr/local/tomcat/logs/
